EF+FluentAPI (Front)/Models/Order.cs
using System.Text.Json.Serialization;
using EF_FluentAPI__Front_.Models.Intermediate_Entities;

namespace EF_FluentAPI__Front_.Models
{
    public class Order
    {
        public Order()
        {
            OrderDate = DateTime.Now;
        }

        public int Id { get; set; }
        public string Name { get; set; } = null!;
        public decimal TotalPrice { get; set; }
        public DateTime OrderDate { get; set; }
        public string CustomerId { get; set; } = null!;
        public bool IsCompleted { get; set; }

        [JsonIgnore]
        public Customer Customer { get; set; } = null!;
        public ICollection<Product> Products { get; set; } = null!;
        public ICollection<ProductOrder>? ProductOrders { get; set; }

    }
}

EF+FluentAPI (Front)/Controllers/CustomerController.cs
using EF_FluentAPI__Front_.JsonDeserializer;
using EF_FluentAPI__Front_.Models;
using Microsoft.AspNetCore.Mvc;
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Authorization;

namespace EF_FluentAPI__Front_.Controllers
{
    public class CustomerController : Controller
    {
        private readonly string _url;

        public CustomerController(IConfiguration configuration)
        {
            _url = configuration.GetValue<string>("ApiConnectionString:ApiUrl");
        }

        [HttpGet("create")]
        public IActionResult Create()
        {
            return View();
        }        
        
        [HttpPost("create")]
        public async Task<IActionResult> Create([FromForm] Customer customerData)
        {
            using (HttpClient httpClient = new())
            {
                string uri = $"{_url}api/customer/create",
                    requestBody = JsonSerializer.Serialize(customerData);
                httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {Request.Cookies["access_token"]}");
                var httpResponse = await httpClient.PostAsync(uri,
                    new StringContent(requestBody, Encoding.UTF8, "application/json"));

                if ((int)httpResponse.StatusCode != 200)
                {
                    ViewData["ErrorMessage"] = new Deserializer().Deserialize(httpResponse.Content.ReadAsStringAsync().Result);
                    return View();
                }
                Response.Cookies.Append("cid", customerData.Id, new CookieOptions { Expires = DateTime.UtcNow.Add(TimeSpan.FromMinutes(10)) });

                return Redirect("~/");
            }
        }

        [Authorize]
        [HttpGet("profile")]
        public async Task<IActionResult> GetProfile()
        {
            using (HttpClient httpClient = new())
            {
                string uri = $"{_url}api/customer/getById?id={Request.Cookies["cid"]}";
                httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {Request.Cookies["access_token"]}");
                var httpResponse = await httpClient.GetStringAsync(uri);
                
                var customer = JsonSerializer.Deserialize<Customer>(httpResponse,
                    new JsonSerializerOptions(JsonSerializerDefaults.Web))!;

                return View(customer);
            }
        }
    }
}

EF+FluentAPI (Front)/Controllers/OrderController.cs
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using EF_FluentAPI__Front_.JsonDeserializer;
using EF_FluentAPI__Front_.Models;
using EF_FluentAPI__Front_.Sorter;
using Microsoft.AspNetCore.Mvc;

namespace EF_FluentAPI__Front_.Controllers;

public class OrderController : Controller
{
    private readonly string _url;

    public OrderController(IConfiguration configuration)
    {
        _url = configuration.GetValue<string>("ApiConnectionString:ApiUrl");
    }
    
    [HttpPost("confirmed")]
    public async Task<IActionResult> Confirmed()
    {
        using (HttpClient httpClient = new())
        {
            string uri = $"{_url}api/cart/getCart?customerId={Request.Cookies["cid"]}";
            httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {Request.Cookies["access_token"]}");
            var httpResponse = await httpClient.GetStringAsync(uri);

            var cart = JsonSerializer.Deserialize<Cart>(httpResponse,
                new JsonSerializerOptions(JsonSerializerDefaults.Web))!;

            var orderDto = new OrderDto { Products = cart.Products!, TotalPrice = cart.TotalPrice};

            uri = $"{_url}api/order/placeAnOrder?customerId={Request.Cookies["cid"]}";
            var requestBody = JsonSerializer.Serialize(orderDto);
            await httpClient.PostAsync(uri,
                new StringContent(requestBody, Encoding.UTF8, "application/json"));

            return View();
        }
    }
    
    [HttpGet("details")]
    public async Task<IActionResult> Details(string name)
    {
        using (HttpClient httpClient = new())
        {
            string uri = $"{_url}api/order/getByName?name={name}";
            
            try
            {
                var httpResponse = await httpClient.GetStringAsync(uri);
                var order = JsonSerializer.Deserialize<Order>(httpResponse,
                    new JsonSerializerOptions(JsonSerializerDefaults.Web));

                return View(order);
            }
            catch (Exception)
            {
                ViewData["ErrorMessage"] = "Заказ не найден!";
                return View("~/Views/Order/FindOrder.cshtml");
            }
        }
    }

    [HttpGet("find-order")]
    public ActionResult FindOrder()
    {
        return View();
    }

    [HttpPost("finder")]
    public async Task<IActionResult> Finder([FromForm] string number)
    {
        if (number is null)
        {
            ViewData["ErrorMessage"] = "Это поле не может быть пустым!";
            return View("~/Views/Order/FindOrder.cshtml");
        }
        if (Regex.IsMatch(number, @"^\d{6}$"))
            return RedirectToAction("Details", routeValues: new {name = number});
        else if (Regex.IsMatch(number, @"^(\s*)?(\+)?([- _():=+]?\d[- _():=+]?){10,14}(\s*)?$"))
        {
            using (HttpClient httpClient = new())
            {
                if (Regex.IsMatch(number, @"^\d{11}$"))
                    number = number.Substring(1).Insert(0, "+7");
                string uri = $"{_url}api/order/getByCustomerPhone?customerPhone={number}";
                var httpResponse = await httpClient.GetStringAsync(uri);

                var orders = JsonSerializer.Deserialize<ICollection<Order>>(httpResponse,
                    new JsonSerializerOptions(JsonSerializerDefaults.Web));
                if (orders!.Count == 0)
                {
                    ViewData["ErrorMessage"] = "На этот номер не совершались заказы!";
                    return View("~/Views/Order/FindOrder.cshtml");
                }
                
                return View("~/Views/Order/DetailsByPhone.cshtml", orders);
            }
        }
        else
        {
            ViewData["ErrorMessage"] = "Неверный формат данных!";
            return View("~/Views/Order/FindOrder.cshtml");
        }
    }
    
    [HttpGet("sort")]
    public IActionResult Sort(int id)
    {
        var customer = GetOrders().Result;
        var orders = SortingFactory.UseSorter().Sort(customer.Orders!.ToList(), id);
        customer.Orders = orders;
        return View("~/Views/Customer/GetProfile.cshtml", customer);
    }
    
    public async Task<Customer> GetOrders()
    {
        using (HttpClient httpClient = new())
        {
            string uri = $"{_url}api/customer/getById?id={Request.Cookies["cid"]}";

            var httpResponse = await httpClient.GetStringAsync(uri);
            return JsonSerializer.Deserialize<Customer>(httpResponse,
                new JsonSerializerOptions(JsonSerializerDefaults.Web))!;
        }
    }
}

EF+FluentAPI (Front)/Views/Order/Confirmed.cshtml
@{
    ViewData["Title"] = "Заказ оформлен!";
}

<h1>Заказ успешно оформлен!</h1>

<a asp-controller="Customer" asp-action="GetProfile">Посмотреть заказ</a>

EF+FluentAPI (Front)/Views/Order/Details.cshtml
@model Order

@{
    ViewData["Title"] = "Информация по заказу";
}

<h1>Заказ @Model.Name</h1>

<table class="table">
    <thead>
    <tr>
        <th>
            <a>Наименование</a>
        </th>
        <th>
            <a>Цена</a>
        </th>
        <th>
            <a>Количество</a>
        </th>
        <th></th>
    </tr>
    </thead>
    @foreach (var product in Model.Products)
    {
        <tbody>
        <tr>
            <td>
                @Html.DisplayFor(modelItem => product.Name)
            </td>
            <td>
                @{
                    var price = product.Price * product.ProductOrders!.Count;
                    @Html.DisplayFor(modelItem => price)
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => product.ProductOrders!.Count)
            </td>
        </tr>
        </tbody>
    }
    <tr>
        <th>
            <a>Итого: @Model.TotalPrice</a>
        </th>
        <th>
            <a>Дата заказа: @Model.OrderDate</a>
        </th>
    </tr>
</table>

@{
    if (User.Identity!.IsAuthenticated)
    {
        <a asp-controller="Customer" asp-action="GetProfile">Вернуться к заказам</a>
    }
}

EF+FluentAPI (Front)/Views/Order/DetailsByPhone.cshtml
@model ICollection<Order>

<table class="table">
    <thead>
    <tr>
        <th>
            <a>Номер заказа</a>
        </th>
        <th>
            <a>Дата заказа</a>
        </th>
        <th>
            <a>Итоговая цена</a>
        </th>
        <th></th>
    </tr>
    </thead>
    @foreach (var order in Model!)
    {
        <tbody>
        <tr>
            <td>
                @Html.DisplayFor(modelItem => order.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => order.OrderDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => order.TotalPrice)
            </td>
            <td>
                 <a asp-action="Details" asp-controller="Order" asp-route-name=@order.Name>Посмотреть</a>
            </td>
        </tr>
        </tbody>
    }
</table>

EF+FluentAPI (Front)/Views/Order/FindOrder.cshtml
@{
    ViewData["Title"] = "Найти заказ";
}

<h1>Найти заказ</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Finder">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">Введите номер заказа или телефона</label>
                <input name="number" class="form-control" />
                <span class="text-danger"></span>
            </div>
            <font color="#FF1827"><a style="font-size:15px;">@ViewData["ErrorMessage"]</a></font>
            <br />
            <div class="form-group">
                <input type="submit" value="Найти" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}